<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $title;?> </title>
	<script type="text/javascript" src="<?php echo SITE_URL;?>js/jquery-1.6.4.js"></script>
	<link href="<?php echo SITE_URL;?>style/site.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript">
	$(document).ready(function(){
	
		$("select#select1").load("<?php echo SITE_URL;?>ajax/index",{test:""});
	
  	});
	</script>
</head>
<body>
<div id="content">